### ISSUE TITLE
UI Stuck

### ISSUE THREAD

**Issue by AbdullahChauhan** [JankoLancer/geocoder_offline#2]
Hello there,
The issue is when initializing GeocodeData, the UI is stuck for 2/3 secs until it reads the file. Any help!

**Comment by JankoLancer** [comment]
Hi @AbdullahChauhan, the UI is stuck because the file that is provided as an example input file is very big with a lot of location data.

You have few solutions here:
1. If you don't need very precise location data you can use a smaller input data file.
2. You can call GeocoderOffline.init() at the app startup, before UI initialization.
3. You can call GeocoderOffline.init() in another isolate. Keep in mind that data geocoding wants work until isolate finishes the work.

Hope it helps you.

**Comment by AbdullahChauhan** [comment]
Thanks. @JankoLancer. Much appreciated!
Though I didn't know this `GeocoderOffline.init()` exist, is this from latest?

- Actually I solved the problem by similar to your third point. Calling this `GeocodeData(data, 'name', 'country code', 'latitude', 'longitude',
      fieldDelimiter: '\t', eol: '\n')` inside compute and getting the data for once on first call, setting it to instance variable so next, no need to call it again!
